### PR TITLE
tentative fix for issue#229

### PR DESCRIPTION
**Pull request by shlomif**
See: https://github.com/shlomif/PySolFC/issues/229

pygame2 compat.

### CODE REVIEW

**Comment by joeraz** [comment]
Code looks good, and confirmed the music is working in both my Windows and Debian environments.

Looks good to me.

**Comment by joeraz** [comment]
Actually, just found a bug.

When you check/uncheck "Music enabled" in the sound settings dialog, the music doesn't start or stop until the next time PySol restarts.

**Comment by shlomif** [comment]
On Sun, 28 Nov 2021 18:42:36 -0800
"Joe R." ***@***.***> wrote:

> Actually, just found a bug.
> 
> When you check/uncheck "Music enabled" in the sound settings dialog, the
> music doesn't start or stop until the next time PySol restarts.
> 

I'll try to investigate - thanks!

-- 

Shlomi Fish       https://www.shlomifish.org/
Chuck Norris/etc. Facts - https://www.shlomifish.org/humour/bits/facts/

Bigamy: Having one wife too many.
Monogamy: The same thing!           — Unknown source.

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
@joeraz please try again with the recent commit.

**Comment by joeraz** [comment]
Tested again.  All good now.

**Comment by shlomif** [comment]
On Mon, 29 Nov 2021 15:50:29 -0800
"Joe R." ***@***.***> wrote:

> Tested again.  All good now.
> 

Great, thanks!

-- 

Shlomi Fish       https://www.shlomifish.org/
Optimising Code for Speed - https://shlom.in/optimise

Question: What is the difference between Chuck Norris and God?
Answer: Chuck Norris knows he isn’t God.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by joeraz** [comment]
I'd say good to merge then.

**Comment by shlomif** [comment]
Merged from the cmdline. Thanks @joeraz !

**Pull request closed without merging**
