### PR TITLE
add dash-dash-version-cli-flag "--version" - with some tests

### PR DESCRIPTION
**Pull request by shlomif**

### CODE REVIEW

**Comment by joeraz** [comment]
The unit tests pass for me.  Once the Flake8 issues are sorted, all good.

**Comment by shlomif** [comment]
@joeraz - hi, i pushed a commit with a fix. sorry it took me so long

**Comment by joeraz** [comment]
Looks like it's failing in AppVeyor now.

**Comment by shlomif** [comment]
@joeraz : fixed now

**Comment by joeraz** [comment]
Okay, everything looks good to me now.  Ready to merge.

**Pull request closed without merging**
