### PR TITLE
Added an alternate toolkit Kivy

### PR DESCRIPTION
**Pull request by lufebe16**
Implements a new UI toolkit, using the kivy framework based on SDL2.
In Addition it also supplies build scripts to build an android app.

Mainly it adds a new subfolder 'kivy'. The code implements the interface
functions defined and tied in in pysollib/pysoltk.py. All changes in common
code are bound to the TOOLKIT == 'kivy' condition.

There are however a few places, where the common code had to be modified
unconditionally.

1) The main program pysol.py had to be changed back to the original version
   as of version 2.0.  The actual variant prevents alternate toolkits from
   beeing executed. It is really important, that the init() call, that reads
   the settings and commandline options is run BEFORE main.py is imported!
   (I'm really wondering why this change was made).

2) In app.py and game.py pysollib.ui.tktile.solverdialog is imported
   without Toolkit selection. But the code is tkinter spezific. Import is
   now bound to TOOLKIT == 'tk'. In all other cases it will be imported
   from pysoltk (as it should be -> docs/README.SOURCES).

5) The setup of redeal images in stack.py with the actual version has
   moved away from method prepareView (in comparison to version 2.0).
   But the new code in method resize is only called when USE_PIL is
   set (see game.py method resizeGame). The old code has now been
   readded there for situations, where USE_PIL is not set.

3) With the new toolkit, gif image format is not supported, because the
   implementation in kivy/SDL is bad and slow, so to say unusable.
   A script is supplied to transform cardsets to bmp format. Once
   applied this leads to duplicate cardsets (by name).  To prevent
   from problems arising hereof when loading cardsets in app.py,
   method initCardsets now checks for duplicates.

4) For all gif images in data/images and data/tiles a corresponding
   png version was added (if not already one existed).

5) Support files setup.py,makefile,MAKEFILE.in have been extended to
   also handle the newly added directories.

The code was originally derived from version 2.0 from sourceforge and
published with bitbucket and f-droid.

### CODE REVIEW

**Comment by shlomif** [comment]
On Thu, 22 Feb 2018 13:30:59 +0000 (UTC)
lufebe16 <notifications@github.com> wrote:

> Implements a new UI toolkit, using the kivy framework based on SDL2.
> In Addition it also supplies build scripts to build an android app.
> 
> Mainly it adds a new subfolder 'kivy'. The code implements the interface
> functions defined and tied in in pysollib/pysoltk.py. All changes in common
> code are bound to the TOOLKIT == 'kivy' condition.

Thanks! I'll try to take a look at it soon.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Emma Watson Factoids - http://shlom.in/emwatson-facts

If you have the same ideas as everybody else, but have them one week earlier
than everyone else — then you will be hailed as a visionary. But if you have
them five years earlier, you will be named a lunatic. ( Barry Jones )

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@lufebe16 : the travis-CI tests are failing. Can you fix them before I merge?

**Comment by lufebe16** [comment]
The travis check should now work. But I have some comments:

- E402 module level import not at top of file:
      Ha! - I now check why this bad change in pysol.py (since v2.0)
      has been applied. The mainline code is sequential code as any
      other code. An automatic test should not propose sequence
      changes as it affects funtionality! A really dangerous
      test that should be removed.
- E128 continuation line under(over)-indented for visual indent:
      should be free. Is a mess and destroys readability (esp. in
      combination with line-lenth restrictions).
- E501 line too long (more > 79 characters):
      79 caracters: a restriction from the last century. End of the
      90ties we got broad screens and have been happy about it.
      Up to 150 characters should be allowed.
- E302 expected 2 blank lines ... (before mainline defs):
      Even after a Comment that is related to the definition (which
      is a good practice). It separates the comment from its subject.

**Comment by shlomif** [comment]
Seems like the tests are still failing locally and on travis:

```
Test Summary Report
-------------------
tests/style/style-trailing-space.t                                             (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
tests/style/py-flake8.t                                                        (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1

```

**Comment by lufebe16** [comment]
My updates were well tested. I had only failures that also occur on the
current master.

This is the output of the tests on my workstation:

PySolFCwork $ sh -x scripts/travis-ci-build >>log.txt
++ perl -lE 'my @p = split/:/,$ENV{PATH}; print join q#:#, grep { ! m#\A/opt/python# } @p;'
+ PATH=/home/lb/perl5/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0:/usr/lib/llvm/5/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/home/lb/bin:/home/lb/scripts
+ make test

   Failed test 'flake8 is happy with the code.'
   at tests/style/py-flake8.t line 49.
 +---+----------------------------------------------------------------------+---+----------+
 | Ln|Got                                                                   | Ln|Expected  |
 +---+----------------------------------------------------------------------+---+----------+
 *  1|'scripts/cardset_viewer.py:68:8: F821 undefined name \'list_box\'     *  1|''        *
 *  2|scripts/cardset_viewer.py:69:19: F821 undefined name \'list_box\'     *   |          |
 *  3|scripts/cardset_viewer.py:69:32: F821 undefined name \'list_box\'     *   |          |
 *  4|scripts/cardset_viewer.py:82:9: F821 undefined name \'canvas\'        *   |          |
 *  5|scripts/cardset_viewer.py:90:23: F821 undefined name \'filter_var\'   *   |          |
 *  6|scripts/cardset_viewer.py:99:24: F821 undefined name \'rotate_var\'   *   |          |
 *  7|scripts/cardset_viewer.py:132:21: F821 undefined name \'zoom_label\'  *   |          |
 *  8|scripts/cardset_viewer.py:135:21: F821 undefined name \'zoom_label\'  *   |          |
 *  9|scripts/cardset_viewer.py:150:13: F821 undefined name \'canvas\'      *   |          |
 * 10|scripts/cardset_viewer.py:155:9: F821 undefined name \'canvas\'       *   |          |
 * 11|scripts/cardset_viewer.py:157:9: F821 undefined name \'label\'        *   |          |
 * 12|scripts/cardset_viewer.py:182:8: F821 undefined name \'list_box\'     *   |          |
 * 13|scripts/cardset_viewer.py:183:19: F821 undefined name \'list_box\'    *   |          |
 * 14|scripts/cardset_viewer.py:183:32: F821 undefined name \'list_box\'    *   |          |
 * 15|scripts/create_iss.py:9:20: E901 SyntaxError: invalid syntax          *   |          |
 * 16|'                                                                     *   |          |
 +---+----------------------------------------------------------------------+---+----------+
 Looks like you failed 1 test of 1.
Traceback (most recent call last):
  File "tests/individually-importing/import_v2_pysollib.pysolgtk.card.py", line 8, in <module>
    import pysollib.pysolgtk.card
  File "./pysollib/pysolgtk/card.py", line 32, in <module>
    from tkcanvas import MfxCanvasGroup, MfxCanvasImage
  File "./pysollib/pysolgtk/tkcanvas.py", line 50, in <module>
    import gnome.canvas as gnomecanvas
ImportError: No module named gnome.canvas
Traceback (most recent call last):
  File "tests/individually-importing/import_v2_pysollib.pysolgtk.menubar.py", line 8, in <module>
    import pysollib.pysolgtk.menubar
  File "./pysollib/pysolgtk/menubar.py", line 39, in <module>
    from selectcardset import SelectCardsetDialogWithPreview
  File "./pysollib/pysolgtk/selectcardset.py", line 38, in <module>
    from tkcanvas import MfxCanvas, MfxCanvasImage
  File "./pysollib/pysolgtk/tkcanvas.py", line 50, in <module>
    import gnome.canvas as gnomecanvas
ImportError: No module named gnome.canvas
Traceback (most recent call last):
  File "tests/individually-importing/import_v2_pysollib.pysolgtk.selectcardset.py", line 8, in <module>
    import pysollib.pysolgtk.selectcardset
  File "./pysollib/pysolgtk/selectcardset.py", line 38, in <module>
    from tkcanvas import MfxCanvas, MfxCanvasImage
  File "./pysollib/pysolgtk/tkcanvas.py", line 50, in <module>
    import gnome.canvas as gnomecanvas
ImportError: No module named gnome.canvas
Traceback (most recent call last):
  File "tests/individually-importing/import_v2_pysollib.pysolgtk.selectgame.py", line 8, in <module>
    import pysollib.pysolgtk.selectgame
  File "./pysollib/pysolgtk/selectgame.py", line 44, in <module>
    from tkcanvas import MfxCanvas
  File "./pysollib/pysolgtk/tkcanvas.py", line 50, in <module>
    import gnome.canvas as gnomecanvas
ImportError: No module named gnome.canvas
Traceback (most recent call last):
  File "tests/individually-importing/import_v2_pysollib.pysolgtk.selecttile.py", line 8, in <module>
    import pysollib.pysolgtk.selecttile
  File "./pysollib/pysolgtk/selecttile.py", line 40, in <module>
    from tkcanvas import MfxCanvas
  File "./pysollib/pysolgtk/tkcanvas.py", line 50, in <module>
    import gnome.canvas as gnomecanvas
ImportError: No module named gnome.canvas
Traceback (most recent call last):
  File "tests/individually-importing/import_v2_pysollib.pysolgtk.tkcanvas.py", line 8, in <module>
    import pysollib.pysolgtk.tkcanvas
  File "./pysollib/pysolgtk/tkcanvas.py", line 50, in <module>
    import gnome.canvas as gnomecanvas
ImportError: No module named gnome.canvas
make: *** [Makefile:78: test] Fehler 1
+ exit -1

The same output as on current master. But there in addition I have
(I corrected them too):

 *  1|'pysollib/games/mahjongg/mahjongg.py:862:35: F812 list comprehension redefines \'i\' from line 854  *  1|''        *
 *  2|pysollib/hint.py:876:29: W503 line break before binary operator                                     *   |          |
 *  3|pysollib/htmllib2.py:26:5: F401 \'entitydefs\' imported but unused                                  *   |          |

It seems, that you run a different version of the tests.

**Comment by shlomif** [comment]
Tests on master pass fine - http://www.shlomifish.org/Files/files/text/master-tests.txt

```
shlomif[PySolFC]:$trunk$ git show | head
commit b937349deb97d6cd78a7c92982a700bbe3082e3a
Author: Roderik Ploszek <roderik.ploszek@gmail.com>
Date:   Sat Feb 24 23:29:29 2018 +0100

    Fix formatting

```

perhaps you added some commits to your master branch?  Here are the test failures on your branch here - http://www.shlomifish.org/Files/files/text/kivy-tests.txt . Did you install Test::TrailingSpace ?

**Comment by lufebe16** [comment]
My workstation has now been updated:

- Installation of the newest versions of flake8 and pyflakes (testing
  branch of the repo).
- The python system default had to be set to python3 (3.5).
- Test::TrailingSpace perl module had to be added in addition for
  that special test.

With this setup the messages from the server could mainly be
reproduced. Corrections have been verified this way.

So here is another trial.

**Comment by shlomif** [comment]
On Thu, 01 Mar 2018 01:34:15 -0800
lufebe16 <notifications@github.com> wrote:

> My workstation has now been updated:
> 
> - Installation of the newest versions of flake8 and pyflakes (testing
>   branch of the repo).
> - The python system default had to be set to python3 (3.5).
> - Test::TrailingSpace perl module had to be added in addition for
>   that special test.
> 
> With this setup the messages from the server could mainly be
> reproduced. Corrections have been verified this way.
> 
> So here is another trial.
> 

thanks! I'm going to check it.

> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://is.gd/i5eMQd - Emma Watson’s Interview for a Software Dev Job

Chuck Norris knows exactly which thing is rotten in the kingdom of Denmark.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Hi!

Sorry to bother you again, but while the tests are passing now, there is a problem that the Solver dialogue at Assist->Solver is always greyed out even when playing freecell or Black Hole solitaire. I checked it on tk or tile. Please restore it there.

**Comment by lufebe16** [comment]
Some deeper test showed the following.

Python2:
  Master shows the menuentry regardless of solver installation
  My version shows the menuentry greyed/enabled as should be.

Python3:
  Master still shows the menuentry regardless of solver installation
  My version show the menuentry greyed in any case (as claimed).


First point:

The menu entry is controlled by pysollib.settings.USE_FREECELL_SOLVER
with initialisation value True. The final value is evaluated in
pysollib.init.init() checking for the presence of fc-solve application.

ui/tktile/menubar.py imports USE_FREECELL_SOLVER when loaded. The imported
value will never change after import, regardless what will be stored in
settings.USE_FREECEL_SOLVER at runtime afterwards.

The current master version imports ui/tktile/menubar.py before running
init(). So its value will always be True.

This bug has been added by commit c3af677cf72100d5628dd2babb02358cbb003e93
on Apr 18 2017 (flake8 adaptations) and resides in pysol.py. If it
is reverted, then the master version behaves exacly the same way than
my version.

In fact my version reverts that change because it also prevents from running
different toolkits (other than tk) such as gtk or the new kivy.

As mentioned earlier, pycodestyle check E402 is dangerous. Unreflected
changes as a result of that message could change functionality (qed.)


Second point:

With python3 one gets (traceback on line 145 (resp. 139 master) uncommented
in pysollib/init.py):
 
Traceback (most recent call last):
  File ".../PySolFCwork/pysollib/init.py", line 144, in init
    if p.stdout.readline().startswith('fc-solve'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

To fix the python3 version something like the following change should
be applied to init():

Replace the line:

 if p.stdout.readline().startswith('fc-solve'): 

by:
  
line = p.stdout.readline()
if sys.version_info >= (3, 0):
       line = line.decode("utf-8")
if line.startswith('fc-solve'):


Further notes:

The kivy version (i.e. ./pysol.py --kivy) runs only with python2. Python3
upgrade could be another project. The android build runs with python3.
In the android app a python2 interpreter is running.

**Comment by shlomif** [comment]
Merged, thanks for your patience and contributions.

**Pull request merged**
