### PR TITLE
changes because of slow loading of bottoms

### PR DESCRIPTION
**Pull request by cardset**
Because ImageTK.PhotoImage and Image.resizing have problems witht zeros in alphachannel, i masked the image to eliminate the 0s

### CODE REVIEW

**Comment by joeraz** [comment]
Code looks good and runs fine.  Okay with me to merge.

**Comment by joeraz** [comment]
The reshuffle logic works, but if I then undo the reshuffle, the cards no longer return to their original positions.

**Comment by joeraz** [comment]
@cardset If you need some assistance with the undo error, I'd advise looking at the code for the game Crescent.  The game Crescent also has a unique redealing method, and uses InvisibleStacks in game.s.internals to temporarily store cards.  If you use moveMove to move cards between stacks, that will undo properly.  In the current code, creating a couple internals may be the only way to accomplish this.  I may take a stab at it a bit later myself if you don't get to it first.

As for the transparency issue.  I did some further testing and found two potential bugs:
- Bottoms do not appear at all in playable preview.
- If multiple cards are too close together, their transparency areas can overlap and become noticeable.  This is especially noticeable if you're using a round cardset, like a Ganjifa deck (see Kali's Game).  Perhaps the masking should only be done with the bottoms for now?

**Comment by cardset** [comment]
No results. :-( 
But i don't want you to wait to long.

> @cardset If you need some assistance with the undo error, I'd advise looking at the code for the game Crescent. The game Crescent also has a unique redealing method, and uses InvisibleStacks in game.s.internals to temporarily store cards. If you use moveMove to move cards between stacks, that will undo properly. In the current code, creating a couple internals may be the only way to accomplish this. I may take a stab at it a bit later myself if you don't get to it first.
> 

I tried it, but failed.
If i get any idea, i try it again.

But if you find earlier some solution.
Feel free to integrate it.

> As for the transparency issue. I did some further testing and found two potential bugs:
> 
>  Bottoms do not appear at all in playable preview.

For some reason class SubsampledImages
is called before resizing.
So we have to allow the double loading
of bottoms until we find another solution.

Please remove the added "if not USE_PIL:"

> 
> If multiple cards are too close together, their transparency areas
> overlap and become noticeable.  This is especially noticeable if you're 
> using a round cardset, like a Ganjifa deck (see Kali's Game).  Perhaps the > 
> masking should only be done with the bottoms for now?
>

Try it!

My solution is only a workaround.
Any alpha other than zero is not completly transparent. 
And if you place one card onto another, the values are adding together.
You can see it better if you try  putalpha(30) 
or higher in this game.

**Comment by joeraz** [comment]
Merged and added some enhancements:

- The way the masking logic works, it wasn't easy to get it to work for only bottoms, so I set it up to check for the median alpha channel value.  This way, it should only trigger for images that have enough transparency for it to be a problem, which won't include most card fronts.
- I was able to get the undo to work in Cruel if you want to try it - though this change did require me to update the game version, so previous saved games won't work.

As for the double loading, I believe the best solution would be to eliminate the usage of SubsampledImages entirely when USE_PIL is true.  This would also have the benefit of allowing us to use better scaling in the playable preview window.

**Comment by cardset** [comment]
Oh, i am too late. :-(

I was able to separate the loadbottoms from resizing bottoms,
so the double loading problem is solved. SubsampledImages work too.

For the masking logic, i have included a simple solution too.
I will look and test during the week which of the two ways is more useful.

I'll watch the game too.
I am very interested in your solution.
Congratulations 

For the testing, look here.
https://github.com/cardset/PySolFC
I don't want to pull, before we decide what to do.

**Comment by joeraz** [comment]
I ran some tests myself and your fixes work fine with me.  They actually make the bottoms for Ganjifa games look nicer.

If you want to open another PR, I'd approve and merge it.  But could you do a rebase against the main repo's latest develop first, just to keep the branching a little cleaner?

**Comment by cardset** [comment]
> I ran some tests myself and your fixes work fine with me. They actually make the bottoms for Ganjifa games look nicer.

Meanwhile i have managed to sort out the bottoms after resizing too,
and we have the speed back again.

I pull after i get the Github thing to work again.

> 
> If you want to open another PR, I'd approve and merge it. But could you do a rebase against the main repo's latest develop first, just to keep the branching a little cleaner?

I use Github Desktop, and did "rebase current branch with origin".
Now i get the messages on the following picture.
Is this safe to do?

GitHubDesktop_eehQS7CPxJ

**Comment by joeraz** [comment]
In this situation, yes.

Force push rewrites revision history which can cause problems for other developers if they're not expecting it.  In this case though, you're the only person working on your fork, and I'm expecting the rebase, so go ahead.

**Comment by cardset** [comment]
I think, things did not work as expected.
As i worked with 2.1.4. before and i rebase to master,
it now wants to send 73 commits instead the one from myself.
Lets see what will happen.

**Pull request merged**
