### PR TITLE
Tk: set window icon

### PR DESCRIPTION
**Pull request by jnumm**
How about this change for v2.8.0 (#151)? I did test it on macOS, Windows 8 and Debian.

### CODE REVIEW

**Comment by shlomif** [comment]
Hi @jnumm !

Thanks for the PR but I am getting an error when trying to run it here on mageia v8 (while git master works fine):

```
shlomif[PySolFC]:$trunk$ python3 pysol.py -g FreeCell --deal ms100000
Traceback (most recent call last):
  File "pysol.py", line 41, in <module>
    sys.exit(main(sys.argv))
  File "/home/shlomif/Download/unpack/games/pysolfc/git/PySolFC/pysollib/main.py", line 422, in main
    r = pysol_init(app, args)
  File "/home/shlomif/Download/unpack/games/pysolfc/git/PySolFC/pysollib/main.py", line 215, in pysol_init
    init_root_window(top, app)
  File "/home/shlomif/Download/unpack/games/pysolfc/git/PySolFC/pysollib/winsystems/x11.py", line 45, in init_root_window
    base_init_root_window(root, app)
  File "/home/shlomif/Download/unpack/games/pysolfc/git/PySolFC/pysollib/winsystems/common.py", line 95, in base_init_root_window
    icons = [loadImage(img) for img in app.dataloader.findAllIconSizes()]
  File "/home/shlomif/Download/unpack/games/pysolfc/git/PySolFC/pysollib/util.py", line 171, in findAllIconSizes
    icondir = self.findDir(os.path.join('images', 'icons'))
  File "/home/shlomif/Download/unpack/games/pysolfc/git/PySolFC/pysollib/util.py", line 177, in findDir
    return self.__findFile(os.path.isdir, filename, subdirs)
  File "/home/shlomif/Download/unpack/games/pysolfc/git/PySolFC/pysollib/util.py", line 149, in __findFile
    raise OSError("DataLoader could not find "+filename+" in " +
OSError: DataLoader could not find images/icons in /usr/share/PySolFC ('',)
shlomif[PySolFC]:$trunk$

```

Can you fix it?

**Comment by jnumm** [comment]
Hi!

Seems like some sort of version mismatch. Is the installation at `/usr/share/PySolFC`from some other version or from a RPM package?

**Comment by shlomif** [comment]
> Hi!
> 
> Seems like some sort of version mismatch. Is the installation at `/usr/share/PySolFC`from some other version or from a RPM package?

Should be from an rpm package:

```
[shlomif@telaviv1 ~]$ rpm -qa 'PySol*' ; rpm -qa 'pysol*'
PySolFC-2.6.4-5.mga8
PySolFC-cardsets-2.0-13.mga8
pysolfc-cardsets-paulodicker-0.0.1-2.mga8
```

**Comment by jnumm** [comment]
This probably only happens when the new code finds a datadir with the layout of a previous release. Is such a scenario something we should support?

Can you please try with PySolFC-2.6.4-5.mga8 removed from the system to see if it works then.

**Comment by shlomif** [comment]
On Fri, 28 Feb 2020 23:11:28 -0800
Juhani Numminen <notifications@github.com> wrote:

> This probably only happens when the new code finds a datadir with the layout
> of a previous release. Is such a scenario something we should support?
> 
> Can you please try with PySolFC-2.6.4-5.mga8 removed from the system to see
> if it works then.
> 

Thanks, it is working now.

I feel we should support it due to the first item here:

https://www.joelonsoftware.com/2007/02/19/seven-steps-to-remarkable-customer-service/


-- 

Shlomi Fish       https://www.shlomifish.org/
Original Riddles - https://www.shlomifish.org/puzzles/

Alan: Hello, Miss Mandrake. I’m Alan. [she shakes his hand.]
John: John. [shakes his hand.]
Alan: We’re mighty vampires.
Selina: [Amusingly] Selina Mandrake, mighty pirate.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by jnumm** [comment]
Shlomi Fish kirjoitti 29.2.2020 klo 10.48:
> On Fri, 28 Feb 2020 23:11:28 -0800
> Juhani Numminen <notifications@github.com> wrote:
> 
>> This probably only happens when the new code finds a datadir with the layout
>> of a previous release. Is such a scenario something we should support?
>>
>> Can you please try with PySolFC-2.6.4-5.mga8 removed from the system to see
>> if it works then.
>>
> 
> Thanks, it is working now.
> 
> I feel we should support it due to the first item here:
> 
> https://www.joelonsoftware.com/2007/02/19/seven-steps-to-remarkable-customer-service/

Fair enough. I pushed a commit to do that.

**Comment by shlomif** [comment]
On Sat, 29 Feb 2020 01:44:26 -0800
Juhani Numminen <notifications@github.com> wrote:

> Shlomi Fish kirjoitti 29.2.2020 klo 10.48:
> > On Fri, 28 Feb 2020 23:11:28 -0800
> > Juhani Numminen <notifications@github.com> wrote:
> >   
> >> This probably only happens when the new code finds a datadir with the
> >> layout of a previous release. Is such a scenario something we should
> >> support?
> >>
> >> Can you please try with PySolFC-2.6.4-5.mga8 removed from the system to see
> >> if it works then.
> >>  
> > 
> > Thanks, it is working now.
> > 
> > I feel we should support it due to the first item here:
> > 
> > https://www.joelonsoftware.com/2007/02/19/seven-steps-to-remarkable-customer-service/
> >  
> 
> Fair enough. I pushed a commit to do that.
> 
> 
> 

Thanks! Let me try.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/open-source/projects/fortune-mod/

Summer Glau gave Richard III a horse free-of-charge and let him keep his
kingdom for himself.
    — http://www.shlomifish.org/humour/bits/facts/Summer-Glau/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Merged, thanks! Sorry it took me so long.

**Pull request merged**
