### PR TITLE
Python3 for Android package

### PR DESCRIPTION
**Pull request by jnumm**
The changes in this branch allow me to build an APK that does work on my phone – to an extent.
The game is still not playable because the cards are all black squares...

This is related to #120. I think the only remaining python2-dependent part is the GTK interface. I've slipped in some python2-to-python3 documentation changes. 

I wonder if @lufebe16 would be comfortable with these changes. I'm not too sure the scripts will run on other peoples' systems at all.

### CODE REVIEW

**Comment by shlomif** [comment]
Hi @jnumm ! Thanks for the patch, but it is hard to review. For example you removed a line from each and every module under `pysollib`. Can you try to avoid including too many unnecessary changes? Thanks!

**Comment by jnumm** [comment]
Hi @shlomif, I've now removed the commit that touched all `pysollib/` files. Number of changed files is now 27. Sorry for the inconveniently large initial patch.

**Comment by shlomif** [comment]
On Wed, 31 Jul 2019 04:52:19 -0700
Juhani Numminen <notifications@github.com> wrote:

> Hi @shlomif, I've now removed the commit that touched all `pysollib/` files.
> Number of changed files is now 27. Sorry for the inconveniently large initial
> patch.
> 

Thanks! I'll do another review.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Chuck Norris/etc. Facts - http://www.shlomifish.org/humour/bits/facts/

Chuck Norris ability to destroy is only matched (and exceeded) by
Summer Glau’s ability to undo his destruction.
    — http://www.shlomifish.org/humour/bits/facts/Summer-Glau/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@jnumm : thanks, looks much better and like a good change. I'd like to wait a little for @lufebe16 's thoughts.

**Comment by shlomif** [comment]
@jnumm: if @lufebe16 does not reply soon, then I'd like to merge it, but as one squashed commit so it will be easy to revert. Will you be ok with that?

**Comment by jnumm** [comment]
@shlomif You're welcome to squash the commits if you prefer.

**Comment by shlomif** [comment]
On Sun, 04 Aug 2019 13:44:14 -0700
Juhani Numminen <notifications@github.com> wrote:

> @shlomif You're welcome to squash the commits if you prefer.
> 

thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Perl Elems to Avoid - http://perl-begin.org/tutorials/bad-elements/

Knuth is not God! Typing “God” into Google and pressing “I’m Feeling Lucky”
will not lead you to his homepage.
    — http://www.shlomifish.org/humour/bits/facts/Knuth/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by lufebe16** [comment]
@jnumm, @shlomif
I just did some short checks of that work locally. After some small changes an android-debug.apk could be built. But as commented earlier, all cards are black. This needs to be investigated.
In general, the way to go is o.k. Some adaptations will also be necessary to make it fit for fdroid builds. Thanks to @jnumm.

**Comment by shlomif** [comment]
On Thu, 08 Aug 2019 08:58:34 -0700
lufebe16 <notifications@github.com> wrote:

> @jnumm, @shlomif
> I just did some short checks of that work locally. After some small changes
> an android-debug.apk could be built. But as commented earlier, all cards are
> black. This needs to be investigated. In general, the way to go is o.k. Some
> adaptations will also be necessary to make it fit for fdroid builds. Thanks
> to @jnumm.
> 

Thanks for the review! I'll squash and rebase.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://is.gd/i5eMQd - Emma Watson’s Interview for a Software Dev Job

Larry Wall is lazy, impatient and full of hubris.
    — http://www.shlomifish.org/humour/bits/facts/Larry-Wall/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Merged, thanks!

**Pull request closed without merging**
