### PR TITLE
MS Windows Binary Installer

### PR DESCRIPTION
**Pull request by Programator2**
Added a new appveyor artifact - Windows installer (issue #58).
Installer includes:

- a few cardsets (based on the 2.0 installer)
- localization (`gmake pot; gmake mo`)

List of cardsets to be bundled is in the `scripts/cardsets_to_bundle` file.

### CODE REVIEW

**Comment by shlomif** [comment]
@Programator2 : thanks! Can you try to maintain better compat with py 2.7? See https://pythonhosted.org/six/ and other resources.

**Comment by Programator2** [comment]
Ok, I'll do that.

**Comment by shlomif** [comment]
On Tue, 20 Mar 2018 08:03:14 +0000 (UTC)
Roderik Ploszek <notifications@github.com> wrote:

> Ok, I'll do that.
> 

thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Emma Watson Factoids - http://shlom.in/emwatson-facts

There are only two hard things in Computer Science: cache invalidation and
naming things.           — Phil Karlton

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by Programator2** [comment]
Now it should also work correctly on Python 2.

**Comment by shlomif** [comment]
On Tue, 20 Mar 2018 15:13:53 -0700
Roderik Ploszek <notifications@github.com> wrote:

> Now it should also work correctly on Python 2.
> 

thanks, I'll take a look.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Apple Inc. is Evil - http://www.shlomifish.org/open-source/anti/apple/

Bugs are too afraid to reproduce on Chuck Norris’ computer. As a result, when
he uses Microsoft Windows, it behaves just like a Linux system.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Merged, thanks!

**Pull request merged**
