### PR TITLE
Update cardset_viewer.py

### PR DESCRIPTION
**Pull request by cardset**
Original doesn't work for me so I redesigned it.
The tool starts in Appdir and searches for valid card sets.
Since not all the sets are always there, I gave him a file list to rummage through the directories. You can also call up the info and the config file. To view the sets, simply click on the name with the mouse or scroll up and down with the arrow keys.

### CODE REVIEW

**Comment by cardset** [comment]
Sorry, don't find where it says what is wrong.

**Comment by shlomif** [comment]
@cardset : thanks for the PR! However, flake8 is unhappy with your changes: https://travis-ci.org/github/shlomif/PySolFC/jobs/740808028 . Please fix and also try to reduce the number of needlessly-changed/removed/added lines.

**Comment by jnumm** [comment]
@cardset I think it's the imports (flake8 with flake8-import-order)
```
$ python3 -m flake8 scripts/cardset_viewer.py 
scripts/cardset_viewer.py:11:1: I201 Missing newline between import groups. 'from six.moves import tkinter' is identified as Third Party and 'from glob import glob' is identified as Stdlib.
scripts/cardset_viewer.py:12:1: I100 Import statements are in the wrong order. 'from tkinter import filedialog' should be before 'from six.moves import tkinter' and in a different group.
scripts/cardset_viewer.py:12:1: I201 Missing newline between import groups. 'from tkinter import filedialog' is identified as Stdlib and 'from six.moves import tkinter' is identified as Third Party.
```

Please use this order for the imports. I changed the filedialog import to keep python2 compatibility.
```python
import os
from glob import glob

from PIL import Image, ImageTk

from six.moves import tkinter
from six.moves import tkinter_tkfiledialog as filedialog  # messagebox
```

Also, in line 150 Config.txt should be lowercase config.txt.

@shlomif as cardset/andsa said, our `make test` does not say what is wrong regarding style. It would be helpful to show **flake8 output** for 'not tidy' files. I'm talking about these lines in the test output:
```
# [checked] scripts/cardset_viewer.py
# not valid at C:/_P5/lib/perl5/Code/TidyAll/Plugin/Flake8.pm line 39.
#   Failed test 'scripts/cardset_viewer.py is tidy'
#   at tests/lib/MyTidyAll.pm line 24.
# not valid at C:/_P5/lib/perl5/Code/TidyAll/Plugin/Flake8.pm line 39.
not ok 258 - scripts/cardset_viewer.py is tidy
```

**Comment by cardset** [comment]
@jnumm 
Thanks, now it works.

> It would be helpful to show flake8 output for 'not tidy' files.

*thumbs.up*

**Comment by shlomif** [comment]
> @jnumm
> Thanks, now it works.
> 
> > It would be helpful to show flake8 output for 'not tidy' files.
> 
> _thumbs.up_

This should hopefully be implemented in the upcoming https://metacpan.org/pod/Code::TidyAll::Plugin::Flake8 v0.4.0. Thanks!

**Pull request closed without merging**
