### PR TITLE
Cardsets tutorial

### PR DESCRIPTION
**Pull request by Neelix57**

### CODE REVIEW

**Comment by shlomif** [comment]
Hi @Neelix57 !

Thanks, but the commit history is still too cluttered **and** the asciidoc markup seems non-idiomatic and basically HTML-like. See: https://asciidoctor.org/docs/ . Please remedy these issues.

**Comment by Neelix57** [comment]
So, I use asciidoc syntax in my document before converting it with asciidoctor, but got the same html code.

**Comment by shlomif** [comment]
Hi @Neelix57 !

> So, I use asciidoc syntax in my document before converting it with asciidoctor, but got the same html code.

Please provide the original `.asciidoc` markup source **before** you input it to asciidoctor. GitHub and other tools should be able to handle it (e.g: [here](https://github.com/shlomif/PySolFC/blob/master/NEWS.asciidoc) or [here](https://github.com/shlomif/fc-solve/blob/master/fc-solve/source/USAGE.asciidoc) ).

**Comment by Neelix57** [comment]
[test.txt](https://github.com/shlomif/PySolFC/files/5322741/test.txt)

**Pull request closed without merging**
