### PR TITLE
Describe order of Ganjifa suits

### PR DESCRIPTION
**Pull request by topimiettinen**
Help for Dashavatara Ganjifa games refer to general Ganjifa help for
order of suits, but it was actually missing.

### CODE REVIEW

**Comment by topimiettinen** [comment]
I took the suit order from Wikipedia. Image is constructed from card set using ImageMagick `montage -tile 5x2`.

**Comment by topimiettinen** [comment]
CI failures seem unrelated, there are no code changes.

**Comment by topimiettinen** [comment]
@shlomif could you please check the PR?

**Comment by shlomif** [comment]
@topimiettinen : merged, thanks! sorry it took me so long.

**Pull request merged**
