### PR TITLE
remove "import imp/import importlib hybridation"

### PR DESCRIPTION
**Pull request by a-detiste**
this is an other deprecated & removed module

### CODE REVIEW

**Comment by joeraz** [comment]
So these changes break Python 2 compatibility (which I'm okay with, but it will need to be documented).  Can you confirm what the new minimum version of Python to run this updated code would be for said documentation?

**Comment by a-detiste** [comment]
Hi,

I included this in the previous PR, it can be documented at other places too:

```
'classifiers': [
        'Programming Language :: Python :: 3',
    ],
```

**Comment by a-detiste** [comment]
Importlib was backported to python2.7 ... this is very old compatibility code

**Comment by joeraz** [comment]
Yes, but I'm thinking of updating the documentation in files like https://github.com/shlomif/PySolFC/blob/master/README.md or https://github.com/shlomif/PySolFC/blob/master/CONTRIBUTING.md where the Python version requirements are stated for users and contributors.

So would 3.0 be the minimum Python version then?

**Comment by joeraz** [comment]
Tested and it works.  Merging.

Also tested with Python 3.7.  No issues there either - I'll just need to confirm whether the minimum version would be 3.7, 3.0, or something in between.

**Comment by a-detiste** [comment]
Hi. 3.7 as a minimal supported version today is a common/safe choice.

3.0 got very little real world use, even back then (none of the library were ported) and feels weird as an explitly supported version.

**Comment by joeraz** [comment]
Noted.  I'll do that then.

**Pull request merged**
