### PR TITLE
Crossword game

### PR DESCRIPTION
**Pull request by joeraz**
I wrote a version of Crossword solitaire to add to PySol.

### CODE REVIEW

**Comment by shlomif** [comment]
Thanks, Joe! Hopefully someone will review that. I have other priorities:

* https://www.shlomifish.org/humour/Queen-Padme-Tales/teaser/

* https://www.shlomifish.org/philosophy/culture/my-real-person-fan-fiction/take2/

* https://twitter.com/shlomif/status/1336951884268048386

For now, I'm "slaying myself" (or quitting) as the benevolent dictator of pysol (see:
https://www.shlomifish.org/humour/Terminator/Liberation/ongoing-text.html#dedications
) without assigning a successor (but there are 3 other people with git push
bits and I will remain subscribed for now). I may return one day.

**Comment by joeraz** [comment]
Good to know.  I have some other games/features that I was hoping to add, but if the main repo is going to be less active with merging PRs, I may just look into building my fork a bit more for now.

**Comment by joeraz** [comment]
@shlomif Saw your call for contributors.  What would it take if I wanted to join?

Aside from this PR, I have a few more games and features that I built in a branch on my fork, but it doesn't look like anyone's currently reviewing PRs.  Thanks.

**Comment by shlomif** [comment]
@joeraz : I reviewed, tested, and merged it. Thanks! I will give you a commit bit after enough merged PRs. [The more  the merrier](https://www.youtube.com/watch?v=Yf7MT1p1VNI)

**Pull request closed without merging**
