### PR TITLE
Fix system installation

### PR DESCRIPTION
**Pull request by voyageur**
This fixes an import in rules/games table generation, and installs the new pysollib.ui.tktile module

### CODE REVIEW

**Comment by shlomif** [comment]
@voyageur : thanks for your contribution - I'll take a look.

**Comment by shlomif** [comment]
Thanks for your contribution - I merged it now . I'm looking forward to future contributions from you.

**Comment by voyageur** [comment]
And thanks for keeping pysol (with or without fc) alive!

**Comment by shlomif** [comment]
@voyageur : well, I'm happy to keep it as alive as I possibly can because I'm very fond of it. But I fear that I could use much more help with it.

**Comment by voyageur** [comment]
No promise for the long-term, but if I have some free time I can try a few things. Right now I am testing [python3 support](/voyageur/PySolFC/tree/2to3), will see how far I get with it (right now basic games run in python3-only)

**Comment by shlomif** [comment]
@voyageur : hi! Any help is appreciated. I want to convert the code to Python 3.x wholesale, because it seems that Python 2.x is going to be unmaintained. However, the previous time I tried that, I ran into problems with the fact that PySolFC had duplicate code using APIs that were removed in Python 3.x, so I decided to refactor it and get rid of duplicate code first. Can you contribute to this effort as well?

**Pull request merged**
